import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:icos/core/services/edge_function_client.dart';
import 'package:icos/core/services/storage_service.dart';
import 'package:icos/core/utils/date_utils.dart';
import 'package:icos/core/utils/result.dart';
import 'package:icos/features/puzzle/data/puzzle_repository.dart';
import 'package:icos/features/puzzle/domain/models/puzzle.dart';

import '../../../helpers/storage_test_helpers.dart';

Map<String, dynamic> _serverPuzzle(String date) => {
  'id': 'server-$date',
  'puzzle_date': date,
  'grid_size': 5,
  'waypoints': [
    {'order': 1, 'row': 0, 'col': 0},
    {'order': 2, 'row': 4, 'col': 4},
  ],
  'walls': <Object>[],
  'difficulty': 'easy',
  'par_time_seconds': 60,
  'difficulty_score': 1,
};

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late Directory dir;
  final today = AppDateUtils.todayUtc();

  setUp(() async {
    dir = await initTestStorage();
  });

  tearDown(() async {
    await dir.delete(recursive: true);
  });

  PuzzleRepository repoWith(EdgeInvoker invoker) =>
      PuzzleRepository(invoker: invoker);

  test(
    'serves the bundled puzzle, marked bundled, when the server has none',
    () async {
      final repo = repoWith((fn, body) async => const EdgeResponse(500, {}));

      final result = await repo.getPuzzle(today);

      final puzzle = (result as Success<Puzzle, dynamic>).data;
      expect(puzzle.origin, PuzzleOrigin.bundled);
      expect(puzzle.puzzleDate, today);
    },
  );

  test('an archive date with no server puzzle is bundled too', () async {
    final repo = repoWith((fn, body) async => const EdgeResponse(500, {}));

    final result = await repo.getPuzzle('2026-01-02');

    expect(
      (result as Success<Puzzle, dynamic>).data.origin,
      PuzzleOrigin.bundled,
    );
  });

  test(
    'a puzzle generated by the server is a server puzzle and is cached',
    () async {
      final repo = repoWith(
        (fn, body) async => EdgeResponse(200, {'puzzle': _serverPuzzle(today)}),
      );

      final result = await repo.getPuzzle(today);

      expect(
        (result as Success<Puzzle, dynamic>).data.origin,
        PuzzleOrigin.server,
      );
      expect(StorageService.getCachedPuzzle(today), isNotNull);
    },
  );

  test('a cached puzzle is a server puzzle', () async {
    await StorageService.cachePuzzle(today, _serverPuzzle(today));
    final repo = repoWith((fn, body) async => fail('no network expected'));

    final result = await repo.getPuzzle(today);

    expect(
      (result as Success<Puzzle, dynamic>).data.origin,
      PuzzleOrigin.server,
    );
  });

  test('the bundled puzzle is never written to the puzzle cache', () async {
    final repo = repoWith((fn, body) async => const EdgeResponse(500, {}));
    await repo.getPuzzle(today);
    expect(StorageService.getCachedPuzzle(today), isNull);
  });
}
